### ISSUE TITLE
Delete invitation user error if not create

### ISSUE THREAD

**Issue by Balgor18** [benjaminbrassart/transcendence#311]

**Comment by Balgor18** [comment]
Error: 
Invalid this.prisma.matchInvitation.delete() invocation in
/backend/src/game/game.service.ts:130:45

  127 }
  128 
  129 private async _delete_user_invitations(userId: number[]) {
→ 130   await this.prisma.matchInvitation.delete(
An operation failed because it depends on one or more records that were required but not found. Record to delete does not exist.
    at Kr.handleRequestError (/backend/node_modules/@prisma/client/src/runtime/RequestHandler.ts:211:13)
    at Kr.handleAndLogRequestError (/backend/node_modules/@prisma/client/src/runtime/RequestHandler.ts:173:12)
    at Kr.request (/backend/node_modules/@prisma/client/src/runtime/RequestHandler.ts:163:12)
    at PrismaService._request (/backend/node_modules/@prisma/client/src/runtime/getPrismaClient.ts:1036:14)
    at GameService._delete_user_invitations (/backend/src/game/game.service.ts:130:5)
